import type { Metadata } from "next";
import { Geist_Mono, Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import Background from "./_components/Background";
import clsx from "clsx";
import Link from "next/link";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSans = Noto_Sans_KR({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Josajosa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={clsx(geistMono.variable, notoSans.variable, "antialiased")}
      >
        <Background>
          <header className="px-20 py-4 text-2xl">
            <Link href={"/"} className="inline-block w-fit cursor-pointer p-4">
              <h1 className="font-extralight select-none">조사조사</h1>
            </Link>
          </header>
          {children}
        </Background>
      </body>
    </html>
  );
}
